import "~/styles/globals.css";
import { type Metadata } from "next";
import { ThemeProvider } from "~/components/providers/ThemeProvider";
import { ScreenSizeProvider } from "~/components/providers/ScreenSizeProvider";
import NextTopLoader from "nextjs-toploader";

export const metadata: Metadata = {
  title: "Login",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider defaultTheme="dark" storageKey="vite-ui-theme">
          <ScreenSizeProvider>
            <NextTopLoader showSpinner={false}/>
            {children}
          </ScreenSizeProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
